#
# Makefile for HW6
#
# Type  make    to compile all 1 program
# in the homework 
#   
CC=gcc
CFLAGS=-g -std=c99 -pedantic -Wall -Wextra -Wpointer-arith

all: psh6

clean:
	rm -f psh6

psh6: psh6.c 
	$(CC) $(CFLAGS) -o psh6 psh6.c 

