#
# Makefile for HW5
#
# Type  make    to compile all 1 program
# in the homework 
#   
CC=gcc
CFLAGS=-g -std=c99 -pedantic -Wall -Wextra -Wpointer-arith

all: hw5

clean:
	rm -f hw5

hw5: hw5.c 
	$(CC) $(CFLAGS) -o hw5 hw5.c 

